### PR TITLE
WIP GCP support

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
After some research and experimentation I started to write something in Javascript that could be used as a common base for all of our Amplitude needs. Right now this can ingest something from any ReadStream (using `stdin` atm) and outputs newline-delimited JSON to `stdout`. My next step will be adding tests for this, using fixtures derived from prod data. After that, implementing some sort of batching logic for the Batch API/HTTP API/Identify API.

@philbooth what do you think of `lib/transform.js`? Accept a ReadStream, output javascript objects. That should work with marketing and sync events (once we get them using ReadStreams), right?

**Comment by philbooth** [comment]
> @philbooth what do you think of `lib/transform.js`? Accept a ReadStream, output javascript objects. That should work with marketing and sync events (once we get them using ReadStreams), right?

Yep, it looks like a sound approach to me.

**Comment by shane-tomlinson** [comment]
@jbuck is this for train-132?

**Comment by jbuck** [comment]
Yes, hopefully I'll be done by then

**Comment by vladikoff** [comment]
from mtg: train-132

**Pull request closed without merging**
